target-version = "py313"
line-length = 88

[lint]
select = ["E", "W", "F", "I", "B"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.isort]
known-first-party = []

[lint.per-file-ignores]
"__init__.py" = ["F401"]
