name: Lint and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install uv
      run: pip install uv
    - name: Create virtual environment
      run: uv venv
    - name: Install dependencies
      run: uv pip install -r requirements.txt
    - name: Run Ruff
      run: uv run ruff check .
    - name: Run Pytest
      run: uv run pytest -v
