name: Ruff Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a suitable Python version
    - name: Install uv
      run: pip install uv
    - name: Install dependencies
      run: uv pip install -r requirements.txt
    - name: Run Ruff
      run: uv run ruff check .
